import grabStatementsT3 from "../../../Input/logic/excelLogic/grabStatementsT3";

const parameter1 = [
  ",",
  "Statement Number,Statements",
  "1,1. We accept improvements in status and power of lower class  ",
  "2,2. All men expected to try to improve selves                  ",
  "3,3. Success in life by a previously deprived person is resented",
  "4,4. Men can expect fair treatment according to merit           ",
  "5,5. Lower-class not revolutionary                              ",
  '6,"6. Political goals relatively moderate, even conservative     "',
  "7,7. Those born to high place in society should retain it       ",
  "8,8. Person with wealth deserves place in high society          ",
  "9,9. We try to eliminate privileged classes                     ",
  "10,10. We accept aristocratic-type titles and other honors        ",
  '11,"11. The government has its secrets, this is generally accepted "',
  "12,12. Emphasis on publicity in political matters: no secrets     ",
  "13,13. Encouraged to think of ourselves as competing for success  ",
  "14,14. Social status equated with manner of speech                ",
  '15,"15. We take law into our own hands, mob action and vigilantes  "',
  '16,"16. Close ties to Mother Country, as Britain still is for many "',
  "17,17. We prefer companionship and helping hand                   ",
  "18,18. Some disdain for acquiring wealth for its own sake         ",
  "19,19. High value placed on protecting and promoting underdog     ",
  "20,20. We like the idea of a welfare state                        ",
  "21,21. We value the race for success                              ",
  "22,22. Corrupt means of achieving success are accepted            ",
  '23,"23. One law for the rich, another for the poor                 "',
  '24,"24. Lack of respect for the police, and law enforcement        "',
  "25,25. Trust in police has sunk deeply into our national character",
  '26,"26. Worth of a man is judged by what he is, not by education   "',
  '27,"27. Deep respect for the rich, the educated, the social elite  "',
  '28,"28. We are tolerant of popular opinion, don&#39;t like extremes"',
  "29,29. Poor on earth will enjoy higher status in after-life       ",
  "30,30. Respect for civil liberties and minority rights            ",
  "31,31. Virtue tends to be its own reward                          ",
  "32,32. Position of depressed classes must be raised               ",
  "33,33. Emphasis is on getting ahead",
  ""
];

const testValue1 = [
  "1. We accept improvements in status and power of lower class  ",
  "2. All men expected to try to improve selves                  ",
  "3. Success in life by a previously deprived person is resented",
  "4. Men can expect fair treatment according to merit           ",
  "5. Lower-class not revolutionary                              ",
  '"6. Political goals relatively moderate',
  "7. Those born to high place in society should retain it       ",
  "8. Person with wealth deserves place in high society          ",
  "9. We try to eliminate privileged classes                     ",
  "10. We accept aristocratic-type titles and other honors        ",
  '"11. The government has its secrets',
  "12. Emphasis on publicity in political matters: no secrets     ",
  "13. Encouraged to think of ourselves as competing for success  ",
  "14. Social status equated with manner of speech                ",
  '"15. We take law into our own hands',
  '"16. Close ties to Mother Country',
  "17. We prefer companionship and helping hand                   ",
  "18. Some disdain for acquiring wealth for its own sake         ",
  "19. High value placed on protecting and promoting underdog     ",
  "20. We like the idea of a welfare state                        ",
  "21. We value the race for success                              ",
  "22. Corrupt means of achieving success are accepted            ",
  '"23. One law for the rich',
  '"24. Lack of respect for the police',
  "25. Trust in police has sunk deeply into our national character",
  '"26. Worth of a man is judged by what he is',
  '"27. Deep respect for the rich',
  '"28. We are tolerant of popular opinion',
  "29. Poor on earth will enjoy higher status in after-life       ",
  "30. Respect for civil liberties and minority rights            ",
  "31. Virtue tends to be its own reward                          ",
  "32. Position of depressed classes must be raised               ",
  "33. Emphasis is on getting ahead"
];

test("grab statements T3", () => {
  const value1 = grabStatementsT3(parameter1);
  expect(value1).toEqual(testValue1);
});
