import cloneDeep from "lodash/cloneDeep";
import { store } from "react-easy-state";

export default store({
  setState(update) {
    const updateKeys = Object.keys(update);
    for (let i = 0; i < updateKeys.length; i += 1) {
      this[updateKeys[i]] = update[updateKeys[i]];
    }
  },

  getState(value) {
    const returnValue = this[value];
    const newReturnValue = cloneDeep(returnValue);
    return newReturnValue;
  },


  distStateListData: [{"factor":"Factor 1","distStates":[{"factor":"factor1","factorNum":1,"sortValue":-1,"statement":1,"sortStatement":"1. We accept improvements in status and power of lower class  ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor1","factorNum":1,"sortValue":-2,"statement":4,"sortStatement":"4. Men can expect fair treatment according to merit           ","sigLevelText":"P < 0.001","sigLevelRank":5},{"factor":"factor1","factorNum":1,"sortValue":1,"statement":5,"sortStatement":"5. Lower-class not revolutionary                              ","sigLevelText":"P < 0.15","sigLevelRank":1},{"factor":"factor1","factorNum":1,"sortValue":4,"statement":13,"sortStatement":"13. Encouraged to think of ourselves as competing for success  ","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor1","factorNum":1,"sortValue":-1,"statement":17,"sortStatement":"17. We prefer companionship and helping hand                   ","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor1","factorNum":1,"sortValue":-3,"statement":18,"sortStatement":"18. Some disdain for acquiring wealth for its own sake         ","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor1","factorNum":1,"sortValue":-2,"statement":19,"sortStatement":"19. High value placed on protecting and promoting underdog     ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor1","factorNum":1,"sortValue":2,"statement":23,"sortStatement":"23. One law for the rich, another for the poor                 ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor1","factorNum":1,"sortValue":1,"statement":24,"sortStatement":"24. Lack of respect for the police, and law enforcement        ","sigLevelText":"P < 0.15","sigLevelRank":1},{"factor":"factor1","factorNum":1,"sortValue":3,"statement":27,"sortStatement":"27. Deep respect for the rich, the educated, the social elite  ","sigLevelText":"P < 0.01","sigLevelRank":4},{"factor":"factor1","factorNum":1,"sortValue":3,"statement":28,"sortStatement":"28. We are tolerant of popular opinion, don&#39;t like extremes","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor1","factorNum":1,"sortValue":-4,"statement":30,"sortStatement":"30. Respect for civil liberties and minority rights            ","sigLevelText":"P < 0.001","sigLevelRank":5},{"factor":"factor1","factorNum":1,"sortValue":-2,"statement":31,"sortStatement":"31. Virtue tends to be its own reward                          ","sigLevelText":"P < 0.1","sigLevelRank":2},{"factor":"factor1","factorNum":1,"sortValue":-3,"statement":32,"sortStatement":"32. Position of depressed classes must be raised               ","sigLevelText":"P < 0.05","sigLevelRank":3}]},{"factor":"Factor 2","distStates":[{"factor":"factor2","factorNum":2,"sortValue":-3,"statement":3,"sortStatement":"3. Success in life by a previously deprived person is resented","sigLevelText":"P < 0.1","sigLevelRank":2},{"factor":"factor2","factorNum":2,"sortValue":-1,"statement":5,"sortStatement":"5. Lower-class not revolutionary                              ","sigLevelText":"P < 0.15","sigLevelRank":1},{"factor":"factor2","factorNum":2,"sortValue":0,"statement":6,"sortStatement":"6. Political goals relatively moderate, even conservative     ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor2","factorNum":2,"sortValue":-4,"statement":7,"sortStatement":"7. Those born to high place in society should retain it       ","sigLevelText":"P < 0.01","sigLevelRank":4},{"factor":"factor2","factorNum":2,"sortValue":-3,"statement":8,"sortStatement":"8. Person with wealth deserves place in high society          ","sigLevelText":"P < 0.1","sigLevelRank":2},{"factor":"factor2","factorNum":2,"sortValue":3,"statement":9,"sortStatement":"9. We try to eliminate privileged classes                     ","sigLevelText":"P < 0.0001","sigLevelRank":6},{"factor":"factor2","factorNum":2,"sortValue":-4,"statement":10,"sortStatement":"10. We accept aristocratic-type titles and other honors        ","sigLevelText":"P < 0.01","sigLevelRank":4},{"factor":"factor2","factorNum":2,"sortValue":-2,"statement":11,"sortStatement":"11. The government has its secrets, this is generally accepted ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor2","factorNum":2,"sortValue":1,"statement":12,"sortStatement":"12. Emphasis on publicity in political matters: no secrets     ","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor2","factorNum":2,"sortValue":2,"statement":13,"sortStatement":"13. Encouraged to think of ourselves as competing for success  ","sigLevelText":"P < 0.2","sigLevelRank":0},{"factor":"factor2","factorNum":2,"sortValue":-2,"statement":14,"sortStatement":"14. Social status equated with manner of speech                ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor2","factorNum":2,"sortValue":0,"statement":23,"sortStatement":"23. One law for the rich, another for the poor                 ","sigLevelText":"P < 0.15","sigLevelRank":1},{"factor":"factor2","factorNum":2,"sortValue":2,"statement":24,"sortStatement":"24. Lack of respect for the police, and law enforcement        ","sigLevelText":"P < 0.15","sigLevelRank":1},{"factor":"factor2","factorNum":2,"sortValue":3,"statement":26,"sortStatement":"26. Worth of a man is judged by what he is, not by education   ","sigLevelText":"P < 0.05","sigLevelRank":3},{"factor":"factor2","factorNum":2,"sortValue":-2,"statement":27,"sortStatement":"27. Deep respect for the rich, the educated, the social elite  ","sigLevelText":"P < 0.1","sigLevelRank":2},{"factor":"factor2","factorNum":2,"sortValue":0,"statement":28,"sortStatement":"28. We are tolerant of popular opinion, don&#39;t like extremes","sigLevelText":"P < 0.01","sigLevelRank":4},{"factor":"factor2","factorNum":2,"sortValue":1,"statement":33,"sortStatement":"33. Emphasis is on getting ahead","sigLevelText":"P < 0.05","sigLevelRank":3}]}],

  statements: [],
  sortsDisplayText: [],
  isForcedQsortPattern: true,
  dataOrigin: "",
  version: "1.1.0",
  mainDataObject: {},
  gridColDefs: [],
  gridRowData: [],
  numQsorts: 0,
  numCentroidFactors: 7,
  gridColDefsFactorTable: [],
  gridRowDataFactorTable: [],
  eigenvalues: [],
  screePlotData: [],
  gridColDefsFacTableEigen: [],
  gridRowDataFacTableEigen: [],
  shouldDisplayFacKept: false,
  gridColDefsLoadingsTable: [],
  gridRowDataLoadingsTable: [],
  fSigCriterionResults: [],
  numFactorsKeptForRot: undefined,
  unforcedConfirmButtonColor: "orange",
  hasUnforcedBeenConfirmed: false,
  isLoadingFactorsKept: false,
  isLoadingAutoflag: false,
  isLoadingBeginAnalysis: false,
  isDataAlreadyLoaded: false,
  isCentroidLoading: false,
  unforcedRadioButtonState: "forced",
  hasExcelT1Error: false,
  autoFlagHistory: "",
  userSelectedSigLevel: 1.96,
  userSelectedDistStateSigLevel2: 1.96,
  userSelectedDistStateSigLevel1: 2.575,
  distStateLowerValueText: "P < 0.05",
  distStateUpperValueText: "P < 0.01",
  distStateListSortKey: "threshold",
  threshold: 3,
  requireMajorityCommonVariance: true,
  rowClassRulesLoadingsTable: {},
  highlighting: "grays",
  varimaxButtonActive: false,
  userSelectedFactors: [],
  userSelectedRotFactors: [],
  factorCorrelationsTableData: [],
  userSelectedDegreeButtons: [],
  factorCharacteristicsArray: [],
  numbersHaveBeenAppended: false,
  rotationDegrees: 0,
  rotateByDegrees: 10,
  bipolarIndexArray: [],
  highlightDegreeButton1: false,
  highlightDegreeButton2: false,
  highlightDegreeButton3: false,
  highlightDegreeButton4: true,
  highlightDegreeButton5: false,
  shouldShowJudgeRotDiv: false,
  showScatterPlotTableDiv: false,
  showCorrelationMatrix: false,
  showOutputFactorSelection: false,
  showDownloadOutputButtons: false,
  showFactorExtractionButtons: false,
  sendDataToOutputButtonColor: "#d6dbe0",
  showUnrotatedFactorTable: false,
  showEigenvaluesTable: false,
  showScreePlot: false,
  showLoadingsTable: false,
  showKeepFacForRotButton: false,
  showForcedInput: false,
  showJsonFileLoadedMessage: false,
  showExcelErrorModal: false,
  showFactorCorrelationsTable: false,
  showStandardErrorsDifferences: false,
  showFactorCharacteristicsTable: false,
  showErrorMessageBar: false,
  showTableDataNotSentWarning: true,
  showInvertFactorModal: false,
  showFileSaveSuccessDialog: false,
  notifyDataUploadSuccess: false,
  notifyDataSentToOutputSuccess: false,
  notifyForSavedRotation: false,
  isLoadCsvTextButtonGreen: false,
  isLoadCsvQsortsButtonGreen: false,
  isLoadExcelT1ButtonGreen: false,
  isLoadExcelT2ButtonGreen: false,
  isLoadExcelT3ButtonGreen: false,
  isLoadJsonTextButtonGreen: false,
  isLoadJsonQsortsButtonGreen: false,
  isLoadPqmethodTextButtonButtonGreen: false,
  isLoadPqmethodQsortsButtonGreen: false,
  areStatementsLoaded: false,
  areQsortsLoaded: false,
  isInputButtonGreen: false,
  isDataButtonGreen: false,
  isCorrelationsButtonGreen: false,
  isFactorsButtonGreen: false,
  isRotationButtonGreen: false,
  isLoadingsButtonGreen: false,
  isOutputButtonGreen: false,
  isLoadLipsetButtonGreen: false,
  isLoadBuzzwordsButtonGreen: false,
  isLoadMotivationalButtonGreen: false,
  isLoadIpadSurveyButtonGreen: false,
  isLoadingsTableInitialRender: false,
  bipolarSplitCount: 0,
  excelType1NonsymmetricArrayText: "",
  activeStartAnalysisButton: false,
  activeCentroidFactorsButton: false,
  activePcaButton: false,
  calculatingPca: false,
  isFacSelectDisabled: false,
  jsonParticipantId: [],
  outputButtonsArray: ["1", "2", "3", "4", "5", "6", "7", "8"],
  pcaButtonText: "Principal Components",
  varimaxButtonText: "Varimax Rotation",
  isCalculatingVarimax: false,
  disabledPcaButton: false,
  disabledCentroidFactorButton: false,
  shouldIncludeTimestamp: true,
  errorStackTrace: "no stack trace available",
  titleHeight: 30,
  archiveCounter: 0,
  varimaxButtonDisabled: false,
  abFactors: [],
  projectHistoryArray: ["no project loaded"],
  newRotationVectors: [],
  rotColDefsFactorTable: [],
  rotRowDataFactorTable: [],
  customFileNameLocation: "append",
  displayFactorVisualizations: false,
  shouldDisplayFactorVizOptions: false,
  projectName: "unnamed project",
  participantDataObject: false,
  updateFactorVisualizationsButtonColor: "#d6dbe0",
  factorVizOptions: {
    willAddCustomNames: false,
    willAddCustomNameToDownload: false,
    willAdjustCardFontSize: false,
    willAdjustCardFontSizeBy: 13,
    willAdjustCardHeight: false,
    willAdjustCardHeightBy: 110,
    willAdjustCardWidth: false,
    willAdjustCardWidthBy: 110,
    willAdjustDistIndicatorSize: false,
    willAdjustDistIndicatorSizeBy: 12,
    willAdjustIndicatorSize: false,
    willAdjustIndicatorSizeBy: 12,
    willAdjustFontSize: false,
    willAdjustFontSizeBy: 14,
    willAdjustLineSpacing: false,
    willAdjustLineSpacingBy: 1.4,
    willAdjustStatementWidth: false,
    willAdjustStatementWidthBy: 15,
    willAdjustWidthAsian: false,
    willAdjustWidthAsianBy: 12,
    willAdjustTopMargin: false,
    willAdjustTopMarginBy: 5,
    willDisplayConsensusStates: false,
    willDisplayDistingCompareSymbols: true,
    willDisplayOnlyStateNums: false,
    willIncludeLegend: true,
    willIndicateDistinguishing: true,
    willPrependStateNums: false,
    willTrimStatement: true,
    willTrimStatementBy: 5,
    willUseDistingUnicode: true,
    showDistinguishingAs: "symbol",
    consensusIndicator: "#d9effe",
    distinguishingIndicator05: "#ededed",
    distinguishingIndicator01: "#bdbdbd",
    customFactorNames: [],
    customFileNameLocation: "append"
  },
  qSortPattern: [],
  activeValueM6: "",
  activeValueM5: "",
  activeValueM4: "",
  activeValueM3: "",
  activeValueM2: "",
  activeValueM1: "",
  activeValue0: "",
  activeValue1: "",
  activeValue2: "",
  activeValue3: "",
  activeValue4: "",
  activeValue5: "",
  activeValue6: "",
  activeValue7: "",
  activeValue8: "",
  activeValue9: "",
  activeValue10: "",
  activeValue11: "",
  activeValue12: "",
  activeValue13: "",
  qSortPatternObject: {},
  factorVizOptionsHolder: {}
});

/*
"rgba(144,	238, 144, .6)" : "#d6dbe0"};
*/
