import cloneDeep from "lodash/cloneDeep";
import { store } from "react-easy-state";

export default store({
  setState(update) {
    for (const property in update) {
      if (update.hasOwnProperty(property)) {
        this[property] = update[property];
      }
    }
  },

  getState(value) {
    const returnValue = this[value];
    const newReturnValue = cloneDeep(returnValue);
    return newReturnValue;
  },

  statements: [],
  sortsDisplayText: [],
  isForcedQsortPattern: true,
  dataOrigin: "",

  version: "1.0.1",
  mainDataObject: {},
  gridColDefs: [],
  gridRowData: [],
  numQsorts: 0,
  numCentroidFactors: 7,
  gridColDefsFactorTable: [],
  gridRowDataFactorTable: [],
  eigenvalues: [],
  screePlotData: [],
  gridColDefsFacTableEigen: [],
  gridRowDataFacTableEigen: [],
  shouldDisplayFacKept: false,
  gridColDefsLoadingsTable: [],
  gridRowDataLoadingsTable: [],
  fSigCriterionResults: [],
  numFactorsKeptForRot: undefined,
  isLoadingFactorsKept: false,
  isLoadingAutoflag: false,
  isLoadingBeginAnalysis: false,
  isCentroidLoading: false,
  userSelectedSigLevel: 1.96,
  requireMajorityCommonVariance: true,
  rowClassRulesLoadingsTable: {},
  highlighting: "grays",
  varimaxButtonActive: false,
  userSelectedFactors: [],
  userSelectedRotFactors: [],
  factorCorrelationsTableData: [],
  userSelectedDegreeButtons: [],
  factorCharacteristicsArray: [],
  numbersHaveBeenAppended: false,
  rotationDegrees: 0,
  rotateByDegrees: 10,
  bipolarIndexArray: [],
  highlightDegreeButton1: false,
  highlightDegreeButton2: false,
  highlightDegreeButton3: false,
  highlightDegreeButton4: true,
  highlightDegreeButton5: false,
  shouldShowJudgeRotDiv: false,
  showScatterPlotTableDiv: false,
  showCorrelationMatrix: false,
  showOutputFactorSelection: false,
  showDownloadOutputButtons: false,
  showFactorExtractionButtons: false,
  showUnrotatedFactorTable: false,
  showEigenvaluesTable: false,
  showScreePlot: false,
  showLoadingsTable: false,
  showKeepFacForRotButton: false,
  showForcedInput: false,
  showJsonFileLoadedMessage: false,
  showExcelErrorModal: false,
  showFactorCorrelationsTable: false,
  showStandardErrorsDifferences: false,
  showFactorCharacteristicsTable: false,
  showErrorMessageBar: false,
  showTableDataNotSentWarning: true,
  notifyDataUploadSuccess: false,
  bipolarSplitCount: 0,
  excelType1NonsymmetricArrayText: "",
  activeStartAnalysisButton: false,
  activeCentroidFactorsButton: false,
  activePcaButton: false,
  calculatingPca: false,
  isFacSelectDisabled: false,
  jsonParticipantId: [],
  outputButtonsArray: ["1", "2", "3", "4", "5", "6", "7", "8"],
  pcaButtonText: "Extract Principal Components",
  varimaxButtonText: "Varimax Rotation",
  isCalculatingVarimax: false,
  disabledPcaButton: false,
  disabledCentroidFactorButton: false,
  shouldIncludeTimestamp: true,
  errorStackTrace: "no stack trace available",
  titleHeight: 30,
  willAddCustomNames: false,
  willAdjustCardFontSize: false,
  willAdjustCardFontSizeBy: 14,
  willAdjustCardHeight: false,
  willAdjustCardHeightBy: 120,
  willAdjustCardWidth: false,
  willAdjustCardWidthBy: 120,
  willAdjustIndicatorSize: false,
  willAdjustIndicatorSizeBy: 18,
  willAdjustLineSpacing: false,
  willAdjustLineSpacingBy: 12,
  willAdjustStatementWidth: false,
  willAdjustStatementWidthBy: 15,
  willAdjustWidthAsian: false,
  willAdjustWidthAsianBy: 12,
  willDisplayConsensusStates: false,
  willDisplayDistingCompareSymbols: true,
  willDisplayOnlyStateNums: false,
  willIncludeLegend: true,
  willIndicateDistinguishing: true,
  willPrependStateNums: false,
  willTrimStatement: true,
  willTrimStatementBy: 5,
  willUseDistingUnicode: true,
  outputFactorSelectButtonsDisabled: false,
  csvData: false,
  consensusIndicator: {
    r: "232",
    g: "229",
    b: "229",
    a: ".5"
  },
  customFactorNames: [],
  archiveCounter: 0,
  varimaxButtonDisabled: false,
  abFactors: [],
  projectHistoryArray: ["no project loaded"],
  newRotationVectors: [],
  rotColDefsFactorTable: [],
  rotRowDataFactorTable: [],
  customFileNameLocation: "append",
  displayFactorVisualizations: false,
  shouldDisplayFactorVizOptions: false,
  projectName: "unnamed project",
  participantDataObject: false,
  factorVizOptions: {
    willAddCustomNames: false,
    willAdjustCardFontSize: false,
    willAdjustCardFontSizeBy: 14,
    willAdjustCardHeight: false,
    willAdjustCardHeightBy: 120,
    willAdjustCardWidth: false,
    willAdjustCardWidthBy: 120,
    willAdjustIndicatorSize: false,
    willAdjustIndicatorSizeBy: 18,
    willAdjustFontSize: false,
    willAdjustFontSizeBy: 14,
    willAdjustLineSpacing: false,
    willAdjustLineSpacingBy: 12,
    willAdjustStatementWidth: false,
    willAdjustStatementWidthBy: 15,
    willAdjustWidthAsian: false,
    willAdjustWidthAsianBy: 12,
    willDisplayConsensusStates: false,
    willDisplayDistingCompareSymbols: true,
    willDisplayOnlyStateNums: false,
    willIncludeLegend: true,
    willIndicateDistinguishing: true,
    willPrependStateNums: false,
    willTrimStatement: true,
    willTrimStatementBy: 5,
    willUseDistingUnicode: true,
    consensusIndicator: {
      r: "232",
      g: "229",
      b: "229",
      a: ".5"
    },
    customFactorNames: [],
    customFileNameLocation: "append",
    qSortPattern: []
  }
});
